Update compile.yml

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -29,6 +29,8 @@ jobs:
 
       - name: Simula compilazione COBOL
         run: |
+          echo "❌ ERRORE: sorgente non valido"
+          exit 1
           echo "========================================="
           echo "⚙️  COMPILAZIONE IN CORSO..."
           echo "========================================="
